### ISSUE TITLE
Mappings don't work

### ISSUE THREAD

**Issue by jdsutherland** [Cypher1/nvim-rappel#1]
Mappings aren't working for me (as in, nothing happens when the map is pressed). I've left defaults:

![image](https://cloud.githubusercontent.com/assets/5385846/25186512/8e9b23f0-254a-11e7-9d50-192237cbbd31.png)

Attempting to change them as described isn't working either. 

```
let g:rappel#repl_key   = '<leader>p'
let g:rappel#run_key    = '<leader>P'
let g:rappel#launch_key = '<leader>l'
```

Please let me know if there's anything I can provide to help.

**Comment by jdsutherland** [comment]
Found my own error.

**Comment by Cypher1** [comment]
Glad to hear it. Out of interest, what was it? I might be able to make
things easier to use.

Cheers
